Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "hashicorp/bionic64"
    master.vm.hostname = 'master'
    master.vm.box_url = "hashicorp/bionic64"
    master.vm.network :private_network, ip: "192.168.56.101"
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = "hashicorp/bionic64"
    worker.vm.hostname = 'worker'
    worker.vm.box_url = "hashicorp/bionic64"
    worker.vm.network :private_network, ip: "192.168.56.102"
  end
end
